global:
  slack_api_url: "slack_api_url"

route:
  receiver: "slack id"
  group_by: ["alertname"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  routes:
    - receiver: "slack id"
      group_wait: 10s
      match_re:
        service: dev

receivers:
  - name: "slack id"
    slack_configs:
      - channel: "channel"
        icon_emoji: ":pig:"
        text: "summary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"
